### PR TITLE
Update install instructions and links to Github pages instead of

### PR DESCRIPTION
**Pull request by mtmccrea**
Sourceforge

### CODE REVIEW

**Comment by joslloand** [comment]
Rejected.. for the time being due to conflicts.

**Comment by lossius** [comment]
Is there some information here that we would like to see merged in, so that it would be worthwhile to solve the conflicts?

**Comment by joslloand** [comment]
No... the info (updated sc3-plugins details) is now included on the currently updated page. So, no need to merge.

**Comment by mtmccrea** [comment]
This was a snag in my workflow, working off a fork of the repo which went
out of sync from the upstream master, but I have revised the workflow and
it seems to be working well for the moment.

And the Jekyll _serve_ feature is great to avoid numerous minor commits!

**Pull request closed without merging**
